name: myenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - opencv
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - pytorch=2.2.1
  - torchvision=0.17.1
  - ultralytics=8.2.35
  - pip:
      - fastapi
      - uvicorn
      - python-multipart